### ISSUE TITLE
IR Example doesn't display IR Datagram on Screen

### ISSUE THREAD

**Issue by davehamer** [DeskPi-Team/microcar#1]
From the example:
https://github.com/DeskPi-Team/microcar/blob/main/Individual%20Module/microbit-IR.png

The IR Code does not display on the screen. The same example using the Mind+ software does work, I can also see the infrared receiver LED flashing up so it is not a fault with the remote.

Please could you advise?

**Comment by yoyojacky** [comment]
Could you please paste your code ? just the snapshot will be ok. it seems like you have not dragged the right block to the device .
