### ISSUE TITLE
Update Readme.md to make it clear that the .HEX file can be imported into Microsoft Makecode

### ISSUE THREAD

**Issue by davehamer** [DeskPi-Team/microcar#2]
https://github.com/DeskPi-Team/microcar/blob/main/README.md

Could this file be updated to state that you can import the .hex files from the individual module folder into the extensions section of Microsoft Makecode? This was not immediately apparent and would help future customers.

**Comment by yoyojacky** [comment]
Not sure if it can be imported directly. It may require support and review of a lot of files? I'm not sure, currently each project is independent, we would be happy to add it to Microsoft's repository if possible
